spring:
  profiles:
    include: db
  application:
    name: https://free-angle.oss-cn-beijing.aliyuncs.com/
  server:
    MaxFileSize: 300MB
    MaxRequestSize: 500MB
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# PageHelper配置文件
pagehelper:
  helper-dialect: mysql   # 指定数据库，不指定的话会默认自动检测数据库类型
  params: count=countSql
  # 是否启用分页合理化。
  # 如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；
  # 不启用的，以上两种情况都会返回空数据
  reasonable: true
  support-methods-arguments: true



