#Redis
spring:
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password: 7104
    #Redis连接池配置
    jedis:
      pool:
        max-active: 200   #连接池最大连接数
        max-idle: 10      #最大空闲数
        min-idle: 1       #最小空闲数